export const exercises = [
  {
    id: 'seated-leg-lifts',
    title: 'Seated Leg Lifts',
    duration: 180,
    category: 'Seated',
    bodyPart: 'Legs',
    description: 'Strengthen your legs while seated. Perfect for beginners.',
    steps: [
      'Sit tall in your chair, feet flat on the floor.',
      'Slowly extend your right leg straight out in front.',
      'Hold for 3 seconds. Feel your thigh working.',
      'Lower slowly. Repeat 8 times.',
      'Switch to your left leg. Repeat 8 times.',
      'Rest 30 seconds. One more set if you feel good.',
    ],
  },
  {
    id: 'torso-twists',
    title: 'Torso Twists',
    duration: 120,
    category: 'Seated',
    bodyPart: 'Core',
    description: 'Gently rotate your spine to improve mobility and reduce stiffness.',
    steps: [
      'Sit tall, feet flat on the floor.',
      'Place your hands on your shoulders.',
      'Slowly twist your torso to the right.',
      'Hold 2 seconds. Feel the rotation.',
      'Return to center. Twist to the left.',
      'Repeat 10 times on each side.',
    ],
  },
  {
    id: 'seated-marching',
    title: 'Seated Marching',
    duration: 180,
    category: 'Seated',
    bodyPart: 'Cardio',
    description: 'Get your heart pumping while seated. Fun and accessible.',
    steps: [
      'Sit tall with feet flat on the floor.',
      'Lift your right knee toward your chest.',
      'Lower it down. Lift your left knee.',
      'March at a comfortable pace.',
      'Pump your arms gently as you march.',
      'Keep going. You are doing great.',
    ],
  },
  {
    id: 'neck-release',
    title: 'Neck Release',
    duration: 120,
    category: 'Seated',
    bodyPart: 'Upper Body',
    description: 'Release tension in your neck and shoulders.',
    steps: [
      'Sit tall and relax your shoulders down.',
      'Slowly tilt your head toward your right shoulder.',
      'Hold 15 seconds. Feel the gentle stretch.',
      'Return to center. Tilt to the left.',
      'Hold 15 seconds.',
      'Repeat 2 more times on each side.',
    ],
  },
  {
    id: 'arm-circles',
    title: 'Arm Circles',
    duration: 120,
    category: 'Standing',
    bodyPart: 'Upper Body',
    description: 'Warm up your shoulders and improve range of motion.',
    steps: [
      'Stand with feet shoulder-width apart.',
      'Extend both arms straight out to the sides.',
      'Make small circles forward for 30 seconds.',
      'Reverse direction for 30 seconds.',
      'Try larger circles forward and back.',
      'Shake out your arms. Nice.',
    ],
  },
  {
    id: 'heel-touches',
    title: 'Heel Touches',
    duration: 180,
    category: 'Standing',
    bodyPart: 'Balance',
    description: 'Improve balance and coordination.',
    steps: [
      'Stand tall, hold a chair for support if needed.',
      'Place your right heel in front of your left toes.',
      'Return. Place left heel in front of right toes.',
      'Continue alternating at a steady pace.',
      'Keep your core gently engaged.',
      'Repeat 10 times on each side.',
    ],
  },
  {
    id: 'wall-stand',
    title: 'Wall Stand',
    duration: 300,
    category: 'Standing',
    bodyPart: 'Legs',
    description: 'Build leg strength using a wall for support.',
    steps: [
      'Stand about 2 feet away from a wall.',
      'Lean back until your shoulders touch the wall.',
      'Slide down until knees are at about 45 degrees.',
      'Hold this position. Breathe steadily.',
      'Start with 30 seconds. Build up over time.',
      'Slide back up slowly. Rest and repeat 3 times.',
    ],
  },
  {
    id: 'cat-cow',
    title: 'Cat-Cow Stretch',
    duration: 180,
    category: 'Stretch',
    bodyPart: 'Back',
    description: 'Classic yoga flow to improve spinal flexibility.',
    steps: [
      'Start on hands and knees, or stand and bend forward.',
      'Cow pose: Drop your belly, lift chest and tailbone.',
      'Breathe in deeply. Feel your body expand.',
      'Cat pose: Round your spine up toward the ceiling.',
      'Tuck your chin. Exhale fully.',
      'Flow between cat and cow for 3 minutes.',
    ],
  },
  {
    id: 'wrist-stretch',
    title: 'Wrist Stretch',
    duration: 60,
    category: 'Stretch',
    bodyPart: 'Arms',
    description: 'Prevent wrist pain with gentle daily stretching.',
    steps: [
      'Extend your right arm in front, palm facing up.',
      'Use left hand to gently pull fingers down.',
      'Hold 15 seconds. Feel the forearm stretch.',
      'Flip to palm down, pull fingers toward you.',
      'Hold 15 seconds. Switch hands.',
      'Repeat 2 times for each hand.',
    ],
  },
  {
    id: 'butterfly-stretch',
    title: 'Butterfly Stretch',
    duration: 180,
    category: 'Stretch',
    bodyPart: 'Hips',
    description: 'Open your hips and inner thighs with this gentle stretch.',
    steps: [
      'Sit on the floor or a firm surface.',
      'Bring the soles of your feet together.',
      'Let your knees fall open to the sides.',
      'Hold your feet with your hands.',
      'Sit tall and gently press knees toward the floor.',
      'Hold 30 seconds. Breathe deeply.',
    ],
  },
  {
    id: 'gentle-hamstring',
    title: 'Gentle Hamstring',
    duration: 120,
    category: 'Stretch',
    bodyPart: 'Legs',
    description: 'Loosen tight hamstrings while seated.',
    steps: [
      'Sit on the edge of a sturdy chair.',
      'Extend one leg straight out, heel on the floor.',
      'Keep your back tall and lean slightly forward.',
      'Hold the stretch for 30 seconds.',
      'Switch legs. Repeat 2 times each side.',
      'Do not bounce. Stretch gently and steadily.',
    ],
  },
  {
    id: 'wall-pushups',
    title: 'Wall Push-ups',
    duration: 180,
    category: 'Strength',
    bodyPart: 'Upper Body',
    description: 'Build upper body strength safely using a wall.',
    steps: [
      'Stand about 2 feet from a wall.',
      'Place hands on wall at shoulder height, fingers spread.',
      'Bend elbows, bringing your chest toward the wall.',
      'Push back to the starting position.',
      'Keep your body in a straight line throughout.',
      'Do 10 repetitions. Rest and repeat 2 sets.',
    ],
  },
  {
    id: 'chair-squats',
    title: 'Chair Squats',
    duration: 300,
    category: 'Strength',
    bodyPart: 'Legs',
    description: 'Build leg strength with chair support for safety.',
    steps: [
      'Stand in front of a chair, feet shoulder-width apart.',
      'Bend your knees and hips, lowering slowly.',
      'Lightly touch the chair seat, then stand back up.',
      'Keep your chest up and knees behind your toes.',
      'Use the armrests for support if needed.',
      'Do 8 repetitions. Rest and repeat 2 sets.',
    ],
  },
  {
    id: 'calf-raises',
    title: 'Calf Raises',
    duration: 120,
    category: 'Strength',
    bodyPart: 'Legs',
    description: 'Build ankle stability and calf strength.',
    steps: [
      'Stand tall, hold a wall for balance if needed.',
      'Slowly rise up onto your toes.',
      'Hold for 3 seconds at the very top.',
      'Lower back down slowly and with control.',
      'Keep your body straight. Do not lean forward.',
      'Repeat 15 times. Rest and repeat the set.',
    ],
  },
  {
    id: 'indoor-walk',
    title: 'Indoor Walk',
    duration: 600,
    category: 'Walk',
    bodyPart: 'Cardio',
    description: 'Walk at home to get your body moving.',
    steps: [
      'Find a clear path in your home.',
      'Start walking at a comfortable, easy pace.',
      'Swing your arms naturally as you walk.',
      'Keep your posture tall and your head up high.',
      'Breathe deeply. Enjoy the movement.',
      'Every single step counts toward your health.',
    ],
  },
  {
    id: 'nature-walk',
    title: 'Nature Walk',
    duration: 900,
    category: 'Walk',
    bodyPart: 'Cardio',
    description: 'Step outside for a refreshing walk in nature.',
    steps: [
      'Put on comfortable shoes and head outside.',
      'Start slowly. Gradually increase your pace.',
      'Notice the sights, sounds, and smells around you.',
      'Breathe fresh air into your lungs.',
      'Walk for at least 15 minutes if possible.',
      'Being in nature boosts your mood and energy.',
    ],
  },
];
